[env:lilygo-t-hmi]
platform = espressif32@3.5.0
board = esp32s3box
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
    moononournation/GFX Library for Arduino@^1.3.1
    https://github.com/lucadentella/TOTP-Arduino.git
