[env:lilygo-t-hmi]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_PARALLEL_8_BIT=1
    -DTFT_CS=6
    -DTFT_DC=7
    -DTFT_RST=-1
    -DTFT_WR=8
    -DTFT_RD=-1
    -DTFT_D0=48
    -DTFT_D1=47
    -DTFT_D2=39
    -DTFT_D3=40
    -DTFT_D4=41
    -DTFT_D5=42
    -DTFT_D6=45
    -DTFT_D7=46
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
